#  ================= SQLite ========================================

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3


# ================== PostgreSQL ====================================
# development:
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: heroku_shop_development
#   pool:     5
#   username: heroku_shop
#   password: tamir
#   template: template0

# test:
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: heroku_shop_test
#   pool:     5
#   username: heroku_shop
#   password: tamir
#   template: template0

# production:
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: heroku_shop_production
#   pool:     5
#   username: heroku_shop
#   password: tamir
#   template: template0
# # ======================= MYSQL ======================================

# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: ecommerce_development
#   pool: 5
#   username: root
#   password: tamir
#   host: localhost

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: ecommerce_test
#   pool: 5
#   username: root
#   password: tamir
#   host: localhost

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: ecommerce_production
#   pool: 5
#   username: root
#   password: tamir
#   host: localhost